
export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';

export const AUTH_LOGOUT= 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const NEWPOST_START='NEWPOST_START';
export const NEWPOST_FAIL='NEWPOST_FAIL';
export const NEWPOST_SUCCESS='NEWPOST_SUCCESS';

export const FB_AUTH_CHANGE='FB_AUTH_CHANGE';
export const FB_LOGOUT = 'FB_LOGOUT';

export const UPDATE_URL ='UPDATE_URL';